github 에서 새로운 repository를 생성하고, readme 파일에 간단한 설명을 적었다. 이후 로컬에서 git init, add, commit 을 실행하고 git push 명령어를 이용하여 로컬 레포지토리의 내용을 github 원격 레포지토리로 push 하려 했으나 다음과 같은 오류가 발생하였다.

error. failed to push some refs to '~~~'
hint: Updates were rejected because the remote contains work that you do not have locally.

원인을 파악하고 해결(조치) 방법을 제시하시오

원인 : 깃의 원격 저장소와 현재 로컬 저장소가 동기화되어있지 않기 때문이다.

해결방안: git pull --rebase 원격저장소별칭 master
          (동기화)
